[package]
name = "ch9-devtools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
env_logger = "0.9.0"
error-chain = "0.12.4"
log = "0.4.14"
log4rs = "1.0.0"
syslog = "5.0.0"
