[package]
name = "ch9-devtools-buildtimetooling"
version = "1.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "build.rs"

[build-dependencies]
cc = "1"

[dependencies]
cc = "1.0.71"
error-chain = "0.12.4"
