[package]
name = "compression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
flate2 = "1.0.22"
tar = "0.4.37"
url = "2.2.2"
